### ISSUE TITLE
Add Github auth or other form of authentication

### ISSUE THREAD

**Issue by DanielNoord** [Cppkies-Team/CppkiesModRepository#1]
Upon the recommendation of @hyoretsu I want to add [CookieMonster](https://github.com/Aktanusa/CookieMonster) to the repo to make it more visible to all.
However, I don't have a Discord account and can therefore not login to add the mod.
I have no idea how hard it is to add Github authentication but since most mods will be uploaded to Github and therefore their maintainers will have a Github account I think this could be a valuable addition.

**Comment by TheGLander** [comment]
Hello! I added GitHub account support in caf3df7, so you can login via your GitHub account now and submit Cookie Monster!

**Comment by DanielNoord** [comment]
Thanks! I will do this when I get around to it.

Perhaps it might be good to add a link to the repo to the README. I couldn't find it when I search for CppkiesModRepository on google, so it is difficult to find right now.
